apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lesson-1
  creationTimestamp: null
  labels:
    app: tomcat-webapp
  name: tomcat-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app      : tomcat-webapp          # Service will look for those PODS Labels
        container: tomcat-custom
    spec:
      containers:
        - image          : 950313701701.dkr.ecr.us-east-1.amazonaws.com/lesson-1-tomcat:2022.4.01
          name           : tomcat-container
          imagePullPolicy: Always
          resources      : {}
          ports:
            - containerPort: 8080
status: {}

---

apiVersion: v1
kind: Service
metadata:
  namespace: lesson-1
  name     : tomcat-webapp
  labels:
    run: tomcat-webapp              # Select PODS with those Labels
spec:
  ports:
    - name      : tomcat-listener
      protocol  : TCP
      port      : 80                # Port on Load Balancer
      targetPort: 8080              # Port on POD
  selector:
    app      : tomcat-webapp
    container: tomcat-custom
  type: LoadBalancer