apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-virtualservice-nginx
  namespace: lesson-6
spec:
  hosts:
    - "nginx.m-tim.click"
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: nginx-service
            port:
              number: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-virtualservice-tomcat
  namespace: lesson-6
spec:
  hosts:
    - "tomcat.m-tim.click"
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: tomcat-service
            port:
              number: 80