apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name     : {{ .Release.Name }}-service
  labels:
    run: {{ .Release.Name }}-deployment
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name      : https
      protocol  : {{ .Values.service.protocol }}
      port      : {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-deployment
  type: LoadBalancer