apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.target }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecrets.data.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.data.remoteRef.key }}
        property: {{ .Values.externalSecrets.data.remoteRef.property }}