apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amp
  namespace: argocd
spec:
  destination:
    server: 'https://9B674EF0A0009BFCA1DB6574CAE9DC36.gr7.us-east-1.eks.amazonaws.com'
    namespace: prometheus
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.10.5
    helm:
      releaseName: amp
  project: mtim-lesson-7
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
