apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://13ADA01E6286EDD91499DFD7C36443E8.gr7.us-east-1.eks.amazonaws.com'
  source:
    path: lesson-7/charts/external-secrets
    repoURL: 'git@github.com:imprivata-mtimoshchenko/k8s-lessons.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: mtim-lesson-7
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true