apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.domain.name }}
    http:
      paths:
      - path: {{ .Values.domain.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: {{ .Values.service.port }}