apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name     : {{ .Release.Name }}-service
  labels:
    run: {{ .Release.Name }}-deployment
spec:
  ports:
    - name      : tomcat-listener
      protocol  : {{ .Values.service.protocol }}
      port      : {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-deployment