apiVersion: v2
appVersion: v0.5.2
description: External secret management for Kubernetes
home: https://github.com/external-secrets.yaml/external-secrets.yaml
icon: https://raw.githubusercontent.com/external-secrets.yaml/external-secrets.yaml/main/assets/eso-logo-large.png
keywords:
- kubernetes-external-secrets.yaml
- secrets
kubeVersion: '>= 1.19.0-0'
maintainers:
- email: kellinmcavoy@gmail.com
  name: mcavoyk
name: external-secrets.yaml
type: application
version: 0.5.2
