{{- if .Values.webhook.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "external-secrets.yaml.fullname" . }}-webhook
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "external-secrets.yaml-webhook.labels" . | nindent 4 }}
    external-secrets.io/component : webhook
  {{- with .Values.webhook.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
