namespace: lesson-7

container:
  image        : 950313701701.dkr.ecr.us-east-1.amazonaws.com/lesson-1-tomcat
  tag          : 2022.4.01
  port         : 8080
  replicaCount : 2
  version      : v1

service:
  port      : 443
  targetPort: 8080
  protocol  : TCP
  annotations: {
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http,
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:950313701701:certificate/bb8df1c6-7271-410e-b91f-06c969fc68f4,
    external-dns.alpha.kubernetes.io/hostname: tomcat.m-tim.click
  }