apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name     : {{ .Release.Name }}-service
  labels:
    run: {{ .Release.Name }}-deployment
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:950313701701:certificate/bb8df1c6-7271-410e-b91f-06c969fc68f4"
spec:
  ports:
    - name      : https
      protocol  : {{ .Values.service.protocol }}
      port      : {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-deployment
  type: LoadBalancer