namespace: lesson-7

container:
  image        : 950313701701.dkr.ecr.us-east-1.amazonaws.com/lesson-1-nginx
  tag          : 2022.05.02
  port         : 80
  replicaCount : 3
  version      : v1
  envSecrets:
    name: nginx-secrets
    key:
      - nginx_external_dns
      - nginx_password
      - nginx_username

service:
  port      : 80
  targetPort: 80
  protocol  : TCP
