{{- $secret_key  := .Values.externalSecrets.data.remoteRef.key -}}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.externalSecrets.name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.target }}
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecrets.data.remoteRef.secrets }}
  - secretKey: {{ . }}
    remoteRef:
      property: {{ . }}
      key: {{ $secret_key }}
  {{- end }}