apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mtim-lesson-7
  namespace: argocd
  labels:
    environment: mtim
    owner: mtimoshchenko
    project: aplpha-cortNext
    lessonNumber: lesson-7
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: test project created from argocd CLI
  sourceRepos:
    - 'git@github.com:imprivata-mtimoshchenko/k8s-lessons.git'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://grafana.github.io/helm-charts'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - server: https://9B674EF0A0009BFCA1DB6574CAE9DC36.gr7.us-east-1.eks.amazonaws.com
      name: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'