apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-deployment
    version: {{ .Values.container.version }}
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.container.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}-deployment
        version: {{ .Values.container.version }}
    spec:
      containers:
        - image          : {{ .Values.container.image }}:{{ .Values.container.tag }}
          name           : {{ .Release.Name }}-container
          imagePullPolicy: Always
          resources      : {}
          ports:
            - name: {{ .Release.Name }}-listener
              containerPort: {{ .Values.container.port }}
status: {}