apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name     : {{ .Release.Name }}-service
  labels:
    run: {{ .Release.Name }}-deployment
spec:
  ports:
    - name      : {{ .Release.Name }}-listener
      protocol  : {{ .Values.service.protocol }}
      port      : {{ .Values.service.loadBalancerPort }}
      targetPort: {{ .Values.service.tagretPort }}
  selector:
    app: {{ .Release.Name }}-deployment
  type: {{ .Values.service.type }}