---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: training-cluster
  region: us-east-1

nodeGroups:
  - name: NG-1
    instanceType: t3.small
    desiredCapacity: 1

cloudWatch:
  clusterLogging:
    enableTypes: ["audit"]